name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2023-04-19
version: '9.5.8'
project: 'drupal'
datestamp: 1681922719
